# This is a basic workflow to help you get started with Actions

name: Quota

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master
    paths:
      - 'Readme.md'
      - '.github/pictures/**'                #Uncomment if u use imgges in your Readme.md

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:	
    build:	
        runs-on: ubuntu-latest			
        - name: Setup Python	
          uses: actions/setup-python@v2	
          with:	
            python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax	
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified	
        - name: Install python requirements	
          run: |	
            pip3 install -r github-actions/python_requirements.txt 

        - name: Run python script
          run: |	
            python3 ./Skripte/Impfquotenberechnung.py
      # Commit and push
      - uses: EndBug/add-and-commit@v7.1.1
        with:
          message: 'generated from Readme.md'
